sudo: required
dist: trusty
language: c

cache:
    apt: true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.9 g++-4.9 git build-essential libc6-dev-i386 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

before_script:
  - git submodule update --init --recursive
  - git submodule foreach git pull origin master

script:
  - ./scripts/setup.sh
